import 'package:erp_mobile/core/di/service_locator.dart';

import 'register_module.dart';

/// Global service locator.
///
/// Use `getIt<T>()` from anywhere outside widgets/blocs (which receive deps
/// via constructor) to retrieve a registered dependency. Direct usage inside
/// widgets is discouraged — always inject via `BlocProvider`/constructor.
final GetIt getIt = GetIt.instance;

/// Bootstraps every core dependency into [getIt].
///
/// Call this **once** during app start, before `runApp` and before the
/// feature `register*Module(getIt)` calls. This used to be generated by
/// `injectable` (`injection.config.dart`); the codegen DI framework was
/// removed, so registration is now hand-written in
/// [registerCoreDependencies]. `SharedPreferences` must already be
/// registered by the caller (see `main()`).
GetIt configureDependencies() {
  registerCoreDependencies(getIt);
  return getIt;
}
